### ISSUE TITLE
[Bug] intermittent issue detecting marlin printer

### ISSUE THREAD

**Issue by TomW1605** [cp2004/OctoPrint-EEPROM-Marlin#12]
**Describe the bug**
most of the time when I go to the edit tab it will give the error message "Sorry. This plugin does not work with your machine, only Marlin based firmware." some times it will work but not often.

**Steps To Reproduce**
1. Go to the EEPROM tab
2. See error. this is intermittent and i have not pined down the cause yet.

**Expected behavior**
it works

**Logs**

`octoprint.log`: https://pastebin.com/eVZZWukX (i have remove the server heartbeat entries because the log was too big for pastebin)

**Versions, system information**
**Plugin**:
Version: 2.0.0
**OctoPrint**
Version: 1.5.0rc1
Operating System running OctoPrint: OctoPi

Printer model & firmware version: Prusa i3, Marlin
Browser: Chrome

**Additional context, screenshots, anything else you think might be useful**

**Comment by cp2004** [comment]
I think it happens if you reload the page mid print, since it cannot send the necessary commands to get the info. Vague error messages are also a factor in #9.

I know I keep saying this, but I am midway through a re-write of this plugin, that eliminates these issues by running the data-collection and processing server side. There were a few things ahead of it on the list but I am hoping to pin down some time at the end of this week to really dig into it.

**Comment by TomW1605** [comment]
this happens even when i have not printed all day so i dont think it is that.

**Comment by cp2004** [comment]
When this happens, try sending an `M115` command to the printer. Think the problem is that the plugin does not do anything when you reload the page, *after* the printer is connected. If you send that command and it wakes up, you should then be able to press the buttons to do the right things.

**Comment by TomW1605** [comment]
ok i tested that and yes as soon as i send `M115` it works. might be worth adding a refresh button and slightly altering the error message.

**Comment by cp2004** [comment]
> might be worth adding a refresh button and slightly altering the error message

Hehe, I'm going beyond that, writing this issue out entirely. I agree that would be the way to go if I was not re-writing the plugin, but that's exactly what I'm doing 🙂

**Comment by TomW1605** [comment]
that works too thanks for letting me know.
