### ISSUE TITLE
cant scroll through firmware information.. 

### ISSUE THREAD

**Issue by askm76** [cp2004/OctoPrint-EEPROM-Marlin#18]
#### What do you need help with?
i can,t scroll at all in the firmware info screen.. the rest show up fine... jsut installed octoprint and updated last thursday. then i got the update about 15 minutes ago...

**Comment by cp2004** [comment]
Could you send a screenshot/video of the problem? It seems to scroll just fine for me here.

Maybe also a list of other plugins you have installed.

**Comment by vovkas** [comment]
Prolem:
<img width="482" alt="problem" src="https://user-images.githubusercontent.com/35286166/102941433-5de82480-44bb-11eb-8035-a00d08cbc97d.PNG">

**Comment by askm76** [comment]
Sorry. I rebooted both pi and PC. Cleared the cache and it's working now. Thanks for everything..Sent from my Galaxy
-------- Original message --------From: Charlie Powell <notifications@github.com> Date: 2020-12-21  5:02 a.m.  (GMT-05:00) To: cp2004/OctoPrint-EEPROM-Marlin <OctoPrint-EEPROM-Marlin@noreply.github.com> Cc: askm76 <askm76@gmail.com>, Author <author@noreply.github.com> Subject: Re: [cp2004/OctoPrint-EEPROM-Marlin] cant scroll through firmware information..  (#18) 
Could you send a screenshot/video of the problem? It seems to scroll just fine for me here.
Maybe also a list of other plugins you have installed.

**Comment by cp2004** [comment]
@vovkas please open a bug report filling out the *full* information, since that sounds like a different problem to this one (since OP wrote that the rest worked fine)

@askm76 good to hear it's fixed, thanks for reporting back.
