### ISSUE TITLE
Remove whitespace before Firmware Info

### ISSUE THREAD

**Issue by thelewiss1** [cp2004/OctoPrint-EEPROM-Marlin#2]
Hi there, thanks for taking over the plugin.

I've found an issue to query you about:
![image](https://user-images.githubusercontent.com/40576482/95022730-ff0bcf80-0670-11eb-9181-6ab3b82135c2.png)

There is a large amount of whitespace in front of the Firmware Info output.

Thanks!

**Comment by cp2004** [comment]
I am aware of this one, still trying to dig through the code to understand why it appears! It will be fixed at some point.

**Comment by thelewiss1** [comment]
> I am aware of this one, still trying to dig through the code to understand why it appears! It will be fixed at some point.

Great. Thanks!

**Comment by cp2004** [comment]
So while I was able to reproduce this initially, when I went to analyse it to fix, I then couldn't get it to happen 🙁 

Going off code analysis, I added in some bits that trim down the whitespace, at any points I think it *could* turn up.

At some point, please try out the development branch, by installing in 'plugin manager > get more > ...from url' then paste `https://github.com/cp2004/OctoPrint-EEPROM-Marlin/archive/devel.zip` and you should be on the way.

**Comment by thelewiss1** [comment]
> So while I was able to reproduce this initially, when I went to analyse it to fix, I then couldn't get it to happen 🙁
> 
> Going off code analysis, I added in some bits that trim down the whitespace, at any points I think it _could_ turn up.
> 
> At some point, please try out the development branch, by installing in 'plugin manager > get more > ...from url' then paste `https://github.com/cp2004/OctoPrint-EEPROM-Marlin/archive/devel.zip` and you should be on the way.

Hi there!
That's fixed it i believe, i've tried reloading a few times with no preceding whitespace.
Thanks!

**Comment by cp2004** [comment]
Excellent news, thank you for testing it!

**Comment by cp2004** [comment]
2.0.0 Has been released, hopefully you get the update notification
