### ISSUE TITLE
EEPROM Settings Not Available

### ISSUE THREAD

**Issue by GriffinWalmsley** [cp2004/OctoPrint-EEPROM-Marlin#37]
Communication with EEPROM

I am using OctoPrint with the SKR Mini e3 v2 and I have the Marlin EEPROM editor installed. I can view some of the current settings but only the firmware info tab. I also have not been able to make any adjustments. I have set the basic settings:

#define EEPROM_SETTINGS
#define DISABLE_M503
#define EEPROM_CHITCHAT

I don't understand why the rest of the settings do not appear. Am I doing something wrong?

I have attached a picture of the interface that I am seeing.

![EEPROMEditor](https://user-images.githubusercontent.com/63424753/112061571-e9556e00-8b1b-11eb-942c-b87e38b3cbdc.jpg)

**Comment by cp2004** [comment]
Please press the load button, then copy the contents of the terminal to somewhere like https://gist.github.com and link the file.

![image](https://user-images.githubusercontent.com/31997505/112062710-30615480-8b58-11eb-8aff-bba6b35c28d8.png)

![image](https://user-images.githubusercontent.com/31997505/112062760-42db8e00-8b58-11eb-84fd-5baf221dbbc4.png)

**Comment by cp2004** [comment]
Actually, I look again - `#define DISABLE_M503` must be **uncommented**. The plugin uses M503 to get the data out of the printer.

**Comment by cp2004** [comment]
@GriffinWalmsley friendly ping, did the above make sense?

**Comment by cp2004** [comment]
Going to assume this is sorted, closing the issue. If you have further questions please get back in contact.
