### ISSUE TITLE
[Request] M78 support

### ISSUE THREAD

**Issue by KenLucke** [cp2004/OctoPrint-EEPROM-Marlin#41]
#### Is your feature request related to a problem? Please describe.

Could you please add M78 support to the Advanced Panel, so that printer stats show from the last time a "load" is done?  Not exactly EEPROM, as clearing the EEPROM doesn't reset it, but informational nonetheless

Send: M78
Recv: Stats: Prints: 1683, Finished: 1489, Failed: 194
Recv: Stats: Total time: 153d 23h 16m 42s, Longest job: 14d 7h 43m 9s
Recv: Stats: Filament used: 29846.78m

**Comment by cp2004** [comment]
Not an editable thing either? Would probably make more sense on the info tab, if any of them

**Comment by KenLucke** [comment]
Info tab would be fine :)

**Comment by cp2004** [comment]
It's been a while! I had some time to implement this today, so I did!

![image](https://user-images.githubusercontent.com/31997505/141660956-401783cc-a6f0-4c9a-b076-d5e2498bff54.png)

Not sure when it will release, but it will be in 3.2.0.

**Comment by KenLucke** [comment]
Awesome, thank you!

**Comment by cp2004** [comment]
There's a release candidate build available if you want to test it - switch to 'Release Candidate' channel for this plugin in the software update settings in OctoPrint.

Release notes: https://github.com/cp2004/OctoPrint-EEPROM-Marlin/releases/tag/3.2.0rc1
Feedback ticket: #56

**Comment by KenLucke** [comment]
Just tried the pre-release.  It shows the "Printer Stats" (M78)" line, but nothing else.  

<img width="685" alt="image" src="https://user-images.githubusercontent.com/57936294/141664346-0a7a899a-cd4f-4750-a940-63b8b80f6c73.png">

I thought it might be a conflict with UI_Customizer, but disabling that gives the same result

<img width="680" alt="image" src="https://user-images.githubusercontent.com/57936294/141664413-cbcf8cf6-18f2-4467-a629-e0343f58e5f8.png">

**Comment by KenLucke** [comment]
Oh, M78, even when went by terminal, is not responding.
