### ISSUE TITLE
[Request]: Under the "Firmware Info" Sort the "Capability" list  by whats enabled aka all "True" at the top of list.

### ISSUE THREAD

**Issue by Glought** [cp2004/OctoPrint-EEPROM-Marlin#47]
### What would you like implemented?

It would be nice  if the Capabilities where sorted by what is enabled 

Instead of this:

Capability | Enabled
-- | --
Leveling Data | True
Host Action Commands | False
Serial Xon Xoff | False
Arcs | False
Software Power | False
Cooler Temperature | False
Meatpack | False
Autolevel | True
Babystepping | True
Autoreport Pos | False
Z Probe | True
Prompt Support | False
Toggle Lights | False
Chamber Temperature | False
Repeat | False
Binary File Transfer | False
Thermal Protection | True
Case Light Brightness | False
Sdcard | True
Motion Modes | False
Autoreport Sd Status | False
Build Percent | False
Print Job | True
Volumetric | True
Runout | False
Autoreport Temp | True
Sd Write | True
Progress | False
Emergency Parser | False
Eeprom | True

to be sorted like this:

Capability | Enabled
-- | --
Leveling Data | True
Autolevel | True
Babystepping | True
Z Probe | True
Thermal Protection | True
Sdcard | True
Print Job | True
Volumetric | True
Autoreport Temp | True
Sd Write | True
Eeprom | True
Host Action Commands | False
Serial Xon Xoff | False
Arcs | False
Software Power | False
Cooler Temperature | False
Meatpack | False
Autoreport Pos | False
Prompt Support | False
Toggle Lights | False
Chamber Temperature | False
Repeat | False
Binary File Transfer | False
Case Light Brightness | False
Motion Modes | False
Autoreport Sd Status | False
Build Percent | False
Runout | False
Progress | False
Emergency Parser | False

**Comment by cp2004** [comment]
I've opted to sort the list alphabetically - it solves an issue with them rearranging (#48), and I think it would be easier for people to check if something is enabled rather than having to look through each cap.
