### ISSUE TITLE
[Request]: Rename backups

### ISSUE THREAD

**Issue by pandel** [cp2004/OctoPrint-EEPROM-Marlin#51]
### What would you like implemented?

Hi!

Please add a button to rename existing backups or at least add a comment. I like to backup my EEPROM settings before and after changing the firmware and it would be very helpful to add some description to a backup.

Regards,
Holger

**Comment by cp2004** [comment]
You can enable custom backup names in the settings, if you want to add the description to them. But you can't currently edit them after they've been backed up. I am not sure if I'll add this or not, it depends on how much spare time I have.
