### ISSUE TITLE
[Request]: Link Firmware info to config value's

### ISSUE THREAD

**Issue by spacecabbie** [cp2004/OctoPrint-EEPROM-Marlin#53]
### What would you like implemented?

I think it would be really nice to link the result of Firmware Info to https://marlinfw.org/meta/gcode/ to specify what a certain setting is related to.

like this: 
https://i.imgur.com/lUVQjIY.png

Could help out but I am limited in programming knowledge so would need some pointers as to where to add the links.

**Comment by cp2004** [comment]
This is an interesting idea - it could also be implemented with the individual EEPROM values as well. That would actually be easier than doing the firmware capabilities lines - they are very crudely just parsed straight out of the printer, it would require a list of 'known' capabilities to match against. Linking to sections of https://marlinfw.org/docs/configuration/configuration.html might also be an option.

I don't have time to do this now, but if someone were to send in a PR, I would love to review it 🙂

**Comment by spacecabbie** [comment]
Wel if you would be willing to help me get started (guide me a bit on how
to write/adjust it) I am happy to get a base going for ya.

**Comment by cp2004** [comment]
It was not as hard as I thought it might have been to implement this one - so I did it 🙂 

A list of the links was manually compiled from the current Marlin source, but otherwise it seems to work nicely:

![image](https://user-images.githubusercontent.com/31997505/141662047-93113d94-f59b-45ff-bba1-1bd2f4ddcf47.png)

**Comment by cp2004** [comment]
Oh and there is also links to the command for each section: 
![image](https://user-images.githubusercontent.com/31997505/141662070-1fc190e5-ebf7-43fa-861d-e38cd6327c03.png)

**Comment by cp2004** [comment]
There's a release candidate build available if you want to test it - switch to 'Release Candidate' channel for this plugin in the software update settings in OctoPrint.

Release notes: https://github.com/cp2004/OctoPrint-EEPROM-Marlin/releases/tag/3.2.0rc1
Feedback ticket: #56

**Comment by spacecabbie** [comment]
> There's a release candidate build available if you want to test it - switch to 'Release Candidate' channel for this plugin in the software update settings in OctoPrint.
> 
> Release notes: https://github.com/cp2004/OctoPrint-EEPROM-Marlin/releases/tag/3.2.0rc1 Feedback ticket: #56

This is Briliant looks awsome and works nice sorry for the late response printer was out of action. Tested it with the new BTT SKR mini e3 V3.0
Ps. some entry's are still missing how can I add those ?

**Comment by deanZZZZZ** [comment]
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/95451596/170448097-8c70fa3e-147f-4b54-95aa-86a39be2d803.png">
