### ISSUE TITLE
Please add MPC to the menu

### ISSUE THREAD

**Issue by SargonofAssyria** [cp2004/OctoPrint-EEPROM-Marlin#68]
### What would you like implemented?

Please add MPC to the menu.

### M503 Response

```gcode
Recv: echo:; Model predictive control:
Recv: echo:  M306 E0 P40.00 C15.88 R0.0901 A0.1688 F0.1873 H0.0036 T200.0
```

**Comment by cp2004** [comment]
See https://github.com/cp2004/OctoPrint-EEPROM-Marlin/releases/tag/3.3.0. Update the plugin!

**Comment by SargonofAssyria** [comment]
Ok, Tnx
