### ISSUE TITLE
[Request]: Add LONG_FILENAME_WRITE_SUPPORT

### ISSUE THREAD

**Issue by jneilliii** [cp2004/OctoPrint-EEPROM-Marlin#69]
### What would you like implemented?

It seems the current Firmware Info doesn't include LONG_FILENAME_WRITE if enabled in Marlin 2.1.2

### M503 Response

```gcode
M503 not relevant, but capabilities report info below...


Cap:LFN_WRITE:1
```
```

**Comment by cp2004** [comment]
Hmm, it should just pull the firmware capability report and show everything that is produced there, split on the underscores and capitalised.

![image](https://user-images.githubusercontent.com/31997505/216771879-a665138e-1704-4df6-bd6c-b38a04de0a00.png)

At the bottom - `Lfn Write`. There's no help link as I haven't specifically added one, but it should show there.

**Comment by jneilliii** [comment]
Apologies, I do see that now,
