### ISSUE TITLE
Support- Willing to pay for your time

### ISSUE THREAD

**Issue by adamsyed10** [cp2004/OctoPrint-EEPROM-Marlin#75]
Hello, I would first like to thank you for the amazing work that you've done. I have a decent amount of monoprice mini delta v2s that I'm donating to a local school's computer lab. However, I am not able to figure out how to reset the "Printed Time" menu to zero. Some of the printers have glitched out printed times and I don't want to look like they're getting printers that have been used 10,000 hours. I want to be able to easily reset "Printed Time" when I factory reset them all. The printers are all in good working condition and have been tested.  Please let me know if you are able to figure out a way. I am willing to send you one of the delta mini v2s as compensation or can pay cash for your time. You can email me at adamsyed10@gmail.com or message me a good way to contact you.  Thanks for reading this and have a great day!  

Best Regards,
Adam

**Comment by cp2004** [comment]
Apologies, this is not something I'll have time to look into (not had any time at all recently), but thanks for the question. I suspect it's stored in some part of the EEPROM, so there's probably a command to reset it somewhere. If you still need help here, I'd look at asking the community such as the Marlin discord server - they'll know or be able to tell you the answer.

Sorry again for not replying to this sooner :(
